name: 构建和推送Docker镜像

on:
  push:
    tags:
      - 'v*'

jobs:
  构建和推送Docker镜像:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Gradlew添加执行权限
        run: chmod +x ./gradlew
      - name: 构建BootJar
        run: ./gradlew clean bootJar
      - name: 设置DockerBuildX
        uses: docker/setup-buildx-action@v3
      - name: 登录Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/blr-free-ai:latest
            ${{ secrets.DOCKER_USERNAME }}/blr-free-ai:${{ github.ref_name }}